services:
  backend:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - hub
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    networks:
      - hub
networks:
  hub: {}
