services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - postgres
