services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./drizzle.config.ts:/app/drizzle.config.ts
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./src/db/migrations:/app/src/db/migrations
    ports:
      - 4000:4000
    depends_on:
      - postgres
